services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  
  
  
  frontend:
    image: awesome/frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    

  backend:
    image: awesome/backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
    depends_on:
      - database
  